### ISSUE TITLE
 Cannot read property 'has' of undefined on verify

### ISSUE THREAD

**Issue by max-mapper** [isRuslan/learn-generators#4]
full terminal output below. I installed using `npm install learn-generators` on node `0.11.15`. `learn-generators run 01.js` works as expected, but verify fails.

```
~/Desktop/learn-generators 🐈  nave use 0.11.x
What version of node?
stable, latest, x.y, or x.y.z > latest
Creating new env named '0.11.x' using node 0.11.15
######################################################################## 100.0%
installed from binary
~/Desktop/learn-generators 🐈  learn-generators run 01.js 
5
6
7
8
9
~/Desktop/learn-generators 🐈  learn-generators verify 01.js 
/usr/local/lib/node_modules/learn-generators/node_modules/workshopper-exercise/exercise.js:79
      return i18n.has(lookup) ? i18n.raw(lookup) :
                 ^
TypeError: Cannot read property 'has' of undefined
    at Object.i18n.i18n.get (/usr/local/lib/node_modules/learn-generators/node_modules/workshopper-exercise/exercise.js:79:18)
    at Object.raw (/usr/local/lib/node_modules/learn-generators/node_modules/workshopper-exercise/node_modules/i18n-core/index.js:49:21)
    at Object.defaultTranslation [as translate] (/usr/local/lib/node_modules/learn-generators/node_modules/workshopper-exercise/node_modules/i18n-core/index.js:28:17)
    at Object.__ (/usr/local/lib/node_modules/learn-generators/node_modules/workshopper-exercise/node_modules/i18n-core/lib/createTranslator.js:34:15)
    at Exercise.transform (/usr/local/lib/node_modules/learn-generators/node_modules/workshopper-exercise/comparestdout.js:53:37)
    at Transform._read (/usr/local/lib/node_modules/learn-generators/node_modules/workshopper-exercise/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/usr/local/lib/node_modules/learn-generators/node_modules/workshopper-exercise/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/usr/local/lib/node_modules/learn-generators/node_modules/workshopper-exercise/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/usr/local/lib/node_modules/learn-generators/node_modules/workshopper-exercise/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/usr/local/lib/node_modules/learn-generators/node_modules/workshopper-exercise/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
~/Desktop/learn-generators 🐈  cat 01
cat: 01: No such file or directory
~/Desktop/learn-generators 🐈  cat 01.js
function *range(from, to) {
  for (var i = from; i < to; i++) yield(i)
}

for (var r of range(5, 10)) {
   console.log( r );
}
 // 5, 6, 7, 8, 9, 10
```

**Comment by isRuslan** [comment]
It looks like a conflicts with `workshopper` and `workshopper-exercise` package versions. 
I updated both to the `@latest`.

**Comment by max-mapper** [comment]
excellent, works now!
